name: build & deploy

on: 
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Package
      run: npm install
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: npm run build
    - name: Test
      run: npm run ci
