name: build & deploy

on: 
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.2
    - name: Build
      run: npm run build
    - name: test
      run: npm run ci
