name: build & test

on: 
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use Node.js 12.13.x
      uses: actions/setup-node@master
      with:
        node-version: 12.13.x
    - name: Install Package
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: ./reports/lcov.info
